apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "suite-auth.fullname" . }}
  labels:
    app: {{ template "suite-auth.name" . }}
    chart: {{ template "suite-auth.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "suite-auth.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "suite-auth.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
        - name: init-suite-jwt-keys
          image: "busybox"
          command: ['sh', '-c', 'until [ "$(wget -qO - suite-jwt-keys:8080/health)" = "{\"status\":\"UP\"}" ]; do echo waiting for myservice; sleep 2; done;']
        # Auth is dependant on idm
        - name: init-suite-idm
          image: "busybox"
          command: ['sh', '-c', 'until [ "$(wget -qO - suite-idm:8080/health)" = "{\"status\":\"UP\"}" ]; do echo waiting for myservice; sleep 2; done;']
        #  Auth is dependant on password
        - name: init-password
          image: "busybox"
          command: ['sh', '-c', 'until [ "$(wget -qO - suite-password:8080/health)" = "{\"status\":\"UP\"}" ]; do echo waiting for myservice; sleep 2; done;']
        - name: pem-jks-converter
{{ include "pem-jks-converter" . | indent 10 }}
          volumeMounts:
          - name: suite-auth-tls
            mountPath: /cert
            readOnly: true
          - name: ca-key-pair
            mountPath: /ca
            readOnly: True
          - name: suite-auth-jks
            mountPath: /jks-secrets
        - name: pg-init-client
{{ include "pg-init-client" . | indent 10 }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.global.registry }}/{{ .Values.global.repository}}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: suite-random-password
                  key: password
          volumeMounts:
          - name: suite-auth-tls
            mountPath: {{ .Values.internalTls.mountPath }}/cert
            readOnly: true
          - name: ca-key-pair
            mountPath: {{ .Values.internalTls.mountPath }}/ca
            readOnly: true
          - name: suite-auth-jks
            mountPath: /tmp/secrets
            readOnly: true
          - name: postgres-password
            mountPath: /tmp/postgresql-secret
            readOnly: true
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: suite-auth-tls
        secret:
          secretName: suite-auth-tls
          items:
            - key: tls.crt
              path: certificate.pem
            - key: tls.key
              path: private_key.pem
      - name: ca-key-pair
        secret:
          secretName: ca-key-pair
          items:
          - key: tls.crt
            path: ca_certificate.pem
      - name: suite-auth-jks
        emptyDir: {}
      - name: postgres-password
        secret:
          secretName: suite-random-password
          items:
          - key: password
            path: postgres-password
